### ISSUE TITLE
[FEATURE] Helm Charts

### ISSUE THREAD

**Issue by JessieAMorris** [philterd/philter#13]
I'd like to deploy this on Kubernetes easily, and Helm is pretty good way to do this. I don't think this is quite perfect, but it is fairly functional for me in my cluster.

https://github.com/JessieAMorris/philterd-charts

Since it's a new repo, I can't make a pull request directly, but would be more than happy to have this be moved into the `philterd` github organization, though.

**Comment by jzonthemtn** [comment]
That's awesome! Thanks for putting it together.

I would love to have it under philterd. I can make you a maintainer on the new repo. Would that be ok?

**Comment by jzonthemtn** [comment]
@JessieAMorris I invinted you to the org. I *think* that should allow you to transfer the repository.

**Comment by jzonthemtn** [comment]
Thank you!! You should have maintainer access to that repo if I got the settings right.
